### ISSUE TITLE
nestjs如何获取post提交的content-type为text/plain的数据？

### ISSUE THREAD

**Issue by ywachao** [nestcn/docs.nestjs.cn#147]
nestjs如何获取post提交的content-type为text/plain的数据？

**Comment by Eraylee** [comment]
推荐使用自定义装饰器来解决此问题

新建一个`plain-body.decorator.ts`文件，安装`raw-body`，然后像这样：
```
import * as rawbody from 'raw-body';
import {
  createParamDecorator,
  HttpException,
  HttpStatus,
} from '@nestjs/common';

export const PlainBody = createParamDecorator(async (data, req) => {
  if (req.readable) {
    return (await rawbody(req)).toString().trim();
  }
  throw new HttpException(
    'Body aint text/plain',
    HttpStatus.INTERNAL_SERVER_ERROR,
  );
});

```
在需要用到的控制器上面，使用 `@PlainBody() `即可。

**Comment by Eraylee** [comment]
0

> 推荐使用自定义装饰器来解决此问题
> 
> 新建一个`plain-body.decorator.ts`文件，安装`raw-body`，然后像这样：
> 
> ```
> import * as rawbody from 'raw-body';
> import {
>   createParamDecorator,
>   HttpException,
>   HttpStatus,
> } from '@nestjs/common';
> 
> export const PlainBody = createParamDecorator(async (data, req) => {
>   if (req.readable) {
>     return (await rawbody(req)).toString().trim();
>   }
>   throw new HttpException(
>     'Body aint text/plain',
>     HttpStatus.INTERNAL_SERVER_ERROR,
>   );
> });
> ```
> 
> 在需要用到的控制器上面，使用 `@PlainBody() `即可。

```
async someFunction(@PlainBody() id: string) {
  .....xxxx
}
```
