### ISSUE TITLE
nest.js 7 中文文档认领

### ISSUE THREAD

**Issue by zuohuadong** [nestcn/docs.nestjs.cn#150]
- [x] 介绍(7/introduction)

- 概述
  - [x]  第一步 (7/firststeps)
  - [x] 控制器 (7/controllers) 
  - [x] 提供者(7/providers) 
  - [x] 模块(7/modules) 
  - [x] 中间件(7/middlewares)
  - [x] 异常过滤器(7/eceptionfilters)
  - [x] 管道(7/pipes) 
  - [x] 守卫(7/guards) 
  - [x] 拦截器(7/interceptors) 
  - [x] 自定义装饰器(7/customdecorators)

- [ ] 基本原理(7/fundamentals)

- [x] 技术(7/techniques)  

- [ ] GraphQL(7/graphql)

- [x] WEBSOCKETS(7/websockets)

- [ ] 微服务(7/microservices)

- [x] 秘籍 (7/recipes) 

- [x] 独立应用(7/standalone-applications)

- [x] CLI (7/cli)

- [x] FAQ (7/faq)

- [x] 迁移指南(7/migrationguide)

- [ ] 谁在使用 Nest (7/discover)

回复：

比如
我要认领翻译「基础-依赖注入」

**Comment by Yaob1990** [comment]
好像很多都没有变化？
第一步我看英文还是 12 个月之前？

**Comment by weizy0219** [comment]
我要认领翻译 [技术]
请问是这样吗？

**Comment by zuohuadong** [comment]
> 我要认领翻译 [技术]
> 请问是这样吗？

认领成功，请提交PR

**Comment by Yaob1990** [comment]
> 我要认领翻译 [技术]
> 请问是这样吗？

技术7都翻译吗？
周末在看配置configuration部分，这部分我可以帮忙翻译哈。

**Comment by zuohuadong** [comment]
> > 我要认领翻译 [技术]
> > 请问是这样吗？
> 
> 技术7都翻译吗？
> 周末在看配置configuration部分，这部分我可以帮忙翻译哈。
 可以先提交哈~

**Comment by weizy0219** [comment]
> > 我要认领翻译 [技术]
> > 请问是这样吗？
> 
> 技术7都翻译吗？
> 周末在看配置configuration部分，这部分我可以帮忙翻译哈。

目前技术部分我刚翻译完数据库部分，您可以先提交。我整个翻译完之后再提交。您这部分我就不改动了。

**Comment by Yocss** [comment]
哎，看 Nest 的中文文档还要就着英文文档一起看，有些翻得根本就不知所云，翻译文档可以有不认识单词，但是英文语法不能不知道啊。

**Comment by weizy0219** [comment]
我要认领翻译[秘籍 (7/recipes)]

**Comment by zuohuadong** [comment]
@weizy0219  认领成功，翻译质量较高，已经给开发者权限。
参考文档：
https://docsify.js.org/#/zh-cn/quickstart

**Comment by Armor-cn** [comment]
我要认领翻译[控制器 ,  提供者,模块 , 中间件,  异常过滤器, 管道 , 守卫 , 拦截器 , 自定义装饰器 ]

**Comment by zuohuadong** [comment]
> 我要认领翻译[控制器 , 提供者,模块 , 中间件, 异常过滤器, 管道 , 守卫 , 拦截器 , 自定义装饰器 ]

申领成功

**Comment by weizy0219** [comment]
我要认领翻译 WEBSOCKETS(7/websockets)，这部分已经翻译完并且提交pull request了

**Comment by weizy0219** [comment]
正在翻译 微服务部分，先认领一下。

**Comment by weizy0219** [comment]
基本原理和微服务部分已翻译完成并提交pr
