### ISSUE TITLE
机翻加百度的文档吗？

### ISSUE THREAD

**Issue by ppxb** [nestcn/docs.nestjs.cn#173]
首先对你们的工作表示敬意和感谢。
今天对graphql的auth有一点不理解，看了下官方文档属实头痛，找到了这个中文文档。点开Guards。人傻了。
![TIM截图20200610133115](https://user-images.githubusercontent.com/17081240/84230704-2fa68700-ab1f-11ea-9a31-d1741feb9aae.png)
![1](https://user-images.githubusercontent.com/17081240/84230701-2f0df080-ab1f-11ea-8643-eee1bfab16eb.png)
![TIM截图20200610133152](https://user-images.githubusercontent.com/17081240/84230702-2f0df080-ab1f-11ea-910a-854b07b554f5.png)
![TIM截图20200610133206](https://user-images.githubusercontent.com/17081240/84230706-2fa68700-ab1f-11ea-98a9-987b02c58c19.png)
![TIM截图20200610133215](https://user-images.githubusercontent.com/17081240/84230715-33d2a480-ab1f-11ea-8f0f-4ba8dbfe7b68.png)
![TIM截图20200610133521](https://user-images.githubusercontent.com/17081240/84230750-42b95700-ab1f-11ea-91d4-43bff594fa5a.png)
文档大概停留在7.0刚release的时候。
Overview几乎全机翻，翻译的时候自己都不读一下看通不通顺吗？不知道谁认领的，这种翻译我一天可以翻100个章节不吹牛逼。
Respect.

**Comment by zuohuadong** [comment]
觉得有问题可以提交PR 。 
感谢...

**Comment by zuohuadong** [comment]
这个查了下，属于可翻，可不翻。
原先是权衡过，如果都不翻的话 ：
对比：
`例如 permissions, roles, ACLs 等`
`例如权限，角色，访问控制列表等 `

后者更好理解。

ACL 全称是： An access-control list  翻译为：访问控制列表  确实没什么问题。
