### ISSUE TITLE
自荐nestjs的例子 nestjs+vue+typescript聊天室

### ISSUE THREAD

**Issue by genaller** [nestcn/docs.nestjs.cn#203]
线上地址： https://genal.fun/
github地址： https://github.com/genaller/genal-chat

**Comment by zuohuadong** [comment]
https://github.com/nestcn/docs.nestjs.cn/blob/master/7/awesome.md
可以提交PR 吗？ 附带下介绍

**Comment by genaller** [comment]
> https://github.com/nestcn/docs.nestjs.cn/blob/master/7/awesome.md
> 可以提交PR 吗？ 附带下介绍

好的
