### ISSUE TITLE
对于旧版（4.6 - 6.x）的 Nest 文档的维护

### ISSUE THREAD

**Issue by finalwhy** [nestcn/docs.nestjs.cn#241]
旧版的 Nest 文档还需要维护或者保留吗？官方文档站并没有对旧文档版本做区分和保留，本仓库作为被官方认证的中文翻译文档应该向其看齐。再者，在维护文档过程中发现一个痛点是对于文档位置的链接，比如目前版本 7 中的不少对于知识板块的链接还是链接到版本 6 下的内容，而同时版本 7 下明明有相同内容，这种情况可能是在推出新版本时维护人员直接将旧版对应部分复制到新版，并对一些文字内容做修改，却忽视了同时应修改链接所导致的（or，当时还没有新版的对应部分）。

所以我认为对于旧版文档不应再保留了，或者至少旧版和新版不应共存在一个分支里。

此为一个讨论，希望各抒己见。如果赞同，我在下一个 pr 里将只保留最新版的文档

**Comment by zuohuadong** [comment]
原先保留是考虑到有些用户没有及时升级系统，一些已经上线的系统，也不便升级。
考虑到此种原因，保留了文档，但是旧版本文档不再维护。
文档位置的链接 这个可以批量替换。

目前三个方案可以讨论：

1. 只保留最新文档。

2. 分支方案，缺点是不能通过网站直接浏览了。

3. 向下兼容一个大版本。

先保留意见。

**Comment by zuohuadong** [comment]
2021年 7.8 更新：增加了 8.x 文档，删除了 5.x 文档。
