### ISSUE TITLE
nest.js 8 中文文档认领

### ISSUE THREAD

**Issue by zuohuadong** [nestcn/docs.nestjs.cn#248]
- [ ] 介绍(8/introduction)

- 概述
  - [ ]  第一步 (8/firststeps)
  - [ ] 控制器 (8/controllers) 
  - [ ] 提供者(8/providers) 
  - [ ] 模块(8/modules) 
  - [ ] 中间件(8/middlewares)
  - [ ] 异常过滤器(8/eceptionfilters)
  - [ ] 管道(8/pipes) 
  - [ ] 守卫(8/guards) 
  - [ ] 拦截器(8/interceptors) 
  - [ ] 自定义装饰器(8/customdecorators) 【待提交】

- [ ] 基本原理(8/fundamentals)

- [ ] 技术(8/techniques)  

- [ ] GraphQL(8/graphql)

- [ ] WEBSOCKETS(8/websockets)

- [ ] 微服务(8/microservices) 【待提交】

- [ ] 秘籍 (8/recipes) 

- [ ] 独立应用(8/standalone-applications)

- [ ] CLI (8/cli)

- [ ] FAQ (8/faq)

- [ ] 迁移指南(8/migrationguide)

- [ ] 谁在使用 Nest (8/discover)

回复：

比如
我要认领翻译「基础-依赖注入」

**Comment by hehu321** [comment]
我要认领翻译

**Comment by ganshiqingyuan** [comment]
我要认领微服务

**Comment by snowyYU** [comment]
我要认领翻译【概述-自定义装饰器】

**Comment by zuohuadong** [comment]
@ganshiqingyuan @snowyYU  认领成功，欢迎提交 PR 。
@hehu321   需要回复认领内容
