### ISSUE TITLE
一个关于文档的疑问

### ISSUE THREAD

**Issue by AqingCyan** [nestcn/docs.nestjs.cn#284]
为什么中文文档的网站形式和官网不太一样，印象里大多数中文文档和原文档的样式都大体一致。这里我有点不解。我明白文档最终的是内容，只是好奇。

**Comment by zuohuadong** [comment]
很多文档，都是把官方的直接拿过来，只翻译 md 文件，后续看 md 文件的更新即可。
虽然，nestjs 官方也提供了md 文件，但官方提交的时候  md 是和 模板混合的，这就给更新加大了工作量。
原先给官方提过一次建议，但仍未采纳。
