### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Cuixote** [nestcn/docs.nestjs.cn#332]
根据这段时间的阅读，有一些可以提升阅读体验的建议。

1. 建议有些特有名词直接使用英文单词，不进行翻译。
如 `controller`不要翻译成控制器。`modules`不要翻译成模块，`provider` 不要翻译成提供者。
比如 `providers` `provider` `provide` 其实是有区别的；而`modules`模块的翻译，太常用了，容易产生歧义。

2. 右侧加入子导航栏，与官网保持一致。

**Comment by zuohuadong** [comment]
感谢提的建议。

1. 原先是中英文一起。 控制器 (controller) 。
但是这样链接不是很好维护。
关于要不要 翻译 过来的问题，可以做个投票吧。    

2. 原先是打算 fork 官网，然后再汉化，但是官方的提交并不标准，经常把样式修改 和 md 文档一起提交。
这就给更新工作带来了很大麻烦。因此使用了 docsify 。
目前受限于 docsify 本身。
