### ISSUE TITLE
5.6翻译校对 认领 (一校)

### ISSUE THREAD

**Issue by zuohuadong** [nestcn/docs.nestjs.cn#38]
> 第一步
> 控制器
> 提供者
> 模块
> 中间件

> 异常过滤器
> 管道

>  守卫

> 拦截器

> 技术

> WEBSOCKETS

> GraphQL
> 执行上下文
> CLI
> FAQ

自定义装饰器
基础

微服务

秘籍

注意： 由于官方文档做了部分更新，一校主要目的是校对官方文档变化的部分。

请回复相应模块名称认领；

**Comment by Erchoc** [comment]
认领：技术。准确来说是技术中的缓存，日志，认证，序列化，Mongo，安全的翻译校对工作

**Comment by Youzhigang** [comment]
基础部分基本查漏补缺了

**Comment by tangkai123456** [comment]
认领: 第一步、控制器、提供者、模块、中间件

**Comment by zuohuadong** [comment]
> 认领: 第一步、控制器、提供者、模块、中间件

已经确认

**Comment by tangkai123456** [comment]
认领: 异常过滤器、管道。
