### ISSUE TITLE
Get confused about the object named `createCatSchema`

### ISSUE THREAD

**Issue by edgexie** [nestcn/docs.nestjs.cn#386]
In the [pipes doc](https://github.com/nestcn/docs.nestjs.cn/blob/master/10/pipes.md) , I get confused about the object named `createCatSchema`, I get it's consult after I  consulted Joi docs. So can we get some supplements？
![image](https://github.com/nestcn/docs.nestjs.cn/assets/18474752/2f1d0cb4-213a-4701-8e57-6a9b3c55d5cc)

**Comment by zuohuadong** [comment]
certainly

**Comment by edgexie** [comment]
> certainly

What I mean is to add an explanation of  `createCatSchema` in the document. HaHa~
