### ISSUE TITLE
6.0 文档校对 认领

### ISSUE THREAD

**Issue by zuohuadong** [nestcn/docs.nestjs.cn#69]
- [x] 介绍(6/introduction)

- 概述
  - [x]  第一步 (6/firststeps)
  - [x] 控制器 (6/controllers)
  - [x] 提供者(6/providers)
  - [x] 模块(6/modules)
  - [x] 中间件(6/middlewares)
  - [x] 异常过滤器(6/exceptionfilters)  
  - [x] 管道(6/pipes)
  - [x] 守卫(6/guards)
  - [x] 拦截器(6/interceptors)
  - [x] 自定义装饰器(6/customdecorators)

- [x] 基本原理(6/fundamentals)

- [x] 技术(6/techniques) 

- [x] GraphQL(6/graphql)

- [x] WEBSOCKETS(6/websockets)

- [x] 微服务(6/microservices)

- [x] 应用上下文(6/applicationcontext)

- [x] 秘籍 (6/recipes)

- [x] CLI (6/cli)【已认领】

- [x] FAQ (6/faq)

- [x] 迁移指南(6/migrationguide)

- [x] 谁在使用 Nest (6/discover)

回复：

比如
我要认领翻译「基础-依赖注入」

**Comment by franken133** [comment]
我要认领翻译 [守卫]

**Comment by zuohuadong** [comment]
> 我要认领翻译 [守卫]

认领成功  ，请直接编辑 https://github.com/nestcn/docs.nestjs.cn/blob/master/6/guards.md  此文件

**Comment by gaoyangy** [comment]
有对应的翻译规范或者要求吗？

**Comment by zuohuadong** [comment]
> 有对应的翻译规范或者要求吗？

https://github.com/nestcn/docs.nestjs.cn/blob/master/6/about.md

**Comment by franken133** [comment]
我已经完成了guard章节的翻译，概述模块还有没开始翻译的章节么？

**Comment by zuohuadong** [comment]
@franken133 
这几天比较忙，其他还没开始，要到下周才能闲一些
我会尽快合并PR 。

**Comment by franken133** [comment]
我认领 管道(6/pipes) 和 拦截器(6/interceptors)

**Comment by zuohuadong** [comment]
> 我认领 管道(6/pipes) 和 拦截器(6/interceptors)

认领成功

**Comment by franken133** [comment]
管道(6/pipes) 和 拦截器(6/interceptors) 已完成。

下面开始翻译异常过滤器(6/exceptionfilters)和自定义装饰器(6/customdecorators)。

@zuohuadong 
请把已完成翻译的模块打上勾，以免重复翻译。

**Comment by gaoyangy** [comment]
我想认领中间件

**Comment by zuohuadong** [comment]
> 我想认领【中间件】

认领成功，请尽量在 4月3日晚 之前完成校对。
感谢。

**Comment by gaoyangy** [comment]
我认领 【基本原理】(6/fundamentals)

**Comment by zuohuadong** [comment]
@gaoyangy
认领成功

**Comment by franken133** [comment]
我认领CLI (6/cli) 这个简单的吧。
争取明天上午之前完成。节后回来继续。

**Comment by zuohuadong** [comment]
> 我认领 【基本原理】(6/fundamentals)

你是按照 官方 最新的 6.0 文档对照的吗？

**Comment by zhangtanlin** [comment]
虽然我也想认领一个，但是水平不够，只是大概能看懂，翻译有点危险。我看你们的进行校验吧，不方便理解的，我提一些意见

**Comment by zuohuadong** [comment]
> 虽然我也想认领一个，但是水平不够，只是大概能看懂，翻译有点危险。我看你们的进行校验吧，不方便理解的，我提一些意见

1. 打开 https://docs.nestjs.com/  找到对应章节，点谷歌翻译。
2. 打开 github 对应的  md 文件。
3. 校对（6.0 有些东西新增了，然后代码有些不一样）
4. 把这句话整理通顺。

标准术语翻译参考： /6/about.md

**Comment by franken133** [comment]
整个秘籍这一章节我认领了秘籍 (6/recipes)

**Comment by zuohuadong** [comment]
> 整个秘籍这一章节我认领了秘籍 (6/recipes)

认领成功

**Comment by zuohuadong** [comment]
> 我想认领【中间件】

@gaoyangy 

中间件一章有问题，没对6.0 的文档

**Comment by gaoyangy** [comment]
@zuohuadong 麻烦问一下，现在还有问题吗？
