### ISSUE TITLE
6.0 二次校对认领

### ISSUE THREAD

**Issue by zuohuadong** [nestcn/docs.nestjs.cn#89]
3- [x] 介绍(6/introduction)

- 概述
  - [x]  第一步 (6/firststeps)
  - [x] 控制器 (6/controllers)
  - [x] 提供者(6/providers)
  - [x] 模块(6/modules)
  - [x] 中间件(6/middlewares)
  - [x] 异常过滤器(6/e ceptionfilters)  
  - [x] 管道(6/pipes)
  - [x] 守卫(6/guards)
  - [x] 拦截器(6/interceptors)
  - [x] 自定义装饰器(6/customdecorators)

- [x] 基本原理(6/fundamentals)

- [x] 技术(6/techniques) 

- [x] GraphQL(6/graphql)

- [x] WEBSOCKETS(6/websockets)

- [x] 微服务(6/microservices)

- [x] 应用上下文(6/applicationconte t)

- [x] 秘籍 (6/recipes)

- [x] CLI (6/cli)【已认领】

- [x] FAQ (6/faq)

- [x] 迁移指南(6/migrationguide)

- [ ] 谁在使用 Nest (6/discover)

回复：

比如
我要认领翻译「基础-依赖注入」

**Comment by baby7305** [comment]
我要认领校对  [介绍]

**Comment by zuohuadong** [comment]
> 我要认领校对[介绍] 
> 每周比对一下官方库文档更新

认领成功，感谢支持。。

**Comment by Jimmysh** [comment]
我要认领校对 [ 管道(6/pipes)]
每周比对一下官方库文档更新

**Comment by RAGGA-TIME** [comment]
我要认领校对 [ 拦截器(6/interceptors) ]  
每周比对一下官方库文档更新

**Comment by zuohuadong** [comment]
@RAGGA-TIME @Jimmysh @warriorsfly  认领成功，请直接提交PR

**Comment by demonarmor** [comment]
我要认领校对 [ 常见问题解答（6 /常见问题）]
每周比对一下官方库文档更新

**Comment by demonarmor** [comment]
我要认领校对[常见问题解答（6 /常见问题）]
每周比对一下官方库文档更新

**Comment by taosher** [comment]
我要认领翻译[自定义装饰器(6/customdecorators)]

**Comment by zuohuadong** [comment]
@taosher  认领成功，请直接提交PR

**Comment by Armor-cn** [comment]
我要认领翻译[微服务(6/microservices)]

**Comment by zuohuadong** [comment]
@Armor-cn  认领成功，请直接提交PR

**Comment by zyu** [comment]
我要认领翻译[模块(6/modules)]

**Comment by zuohuadong** [comment]
@zyu 认领成功，请直接提交PR

**Comment by Armor-cn** [comment]
我要认领翻译[自定义装饰器（6 / customdecorators）]

**Comment by zuohuadong** [comment]
@Armor-cn 认领成功，请直接提交PR

**Comment by zuohuadong** [comment]
@Armor-cn  好了。感谢提醒

**Comment by Armor-cn** [comment]
我要认领翻译[控制器 (6/controllers)]  ,现已更新完成，并已成功提交至pr。

**Comment by Armor-cn** [comment]
我要认领翻译 [提供者(6/providers)]

**Comment by zuohuadong** [comment]
@Armor-cn 高产啊 认领成功

**Comment by Armor-cn** [comment]
哈哈哈，我要认领翻译[中间件(6/middlewares)] ,现已更新完成，并与 提供者(6/providers) 一起提交至pr了。

**Comment by Armor-cn** [comment]
我要认领翻译 [异常过滤器(6/e ceptionfilters) ] [守卫(6/guards)]

**Comment by warriorsfly** [comment]
我要认领翻译[WEBSOCKETS(6/websockets)]

**Comment by zuohuadong** [comment]
@Armor-cn  @warriorsfly  认领成功

**Comment by Armor-cn** [comment]
@zuohuadong  
![image](https://user-images.githubusercontent.com/31821714/66759976-c90b9380-eed3-11e9-9afa-80b37b177ee5.png)

**Comment by Armor-cn** [comment]
我要认领翻译 [基本原理(6/fundamentals)]

**Comment by zuohuadong** [comment]
> 我要认领翻译 [基本原理(6/fundamentals)]

认领成功

**Comment by Armor-cn** [comment]
我要认领翻译 [技术(6/techniques) WEBSOCKETS(6/websockets)]

**Comment by zuohuadong** [comment]
> 我要认领翻译 [技术(6/techniques) WEBSOCKETS(6/websockets)]

高产一哥，认领成功

**Comment by Armor-cn** [comment]
王春明 
上海新致软件股份有限公司
电话：15685116918  
邮箱：chunming.wang@newtouch.cn
地址：上海市陆家嘴软件园1号研发楼
新致软件 www.newtouch.cn 
日新以致远 CMMI5 IS027001
  
       新致官方微信


 




------------------ 原始邮件 ------------------
发件人: "huadong zuo"<notifications@github.com>; 
发送时间: 2019年10月30日(星期三) 中午11:03
收件人: "nestcn/docs.nestjs.cn"<docs.nestjs.cn@noreply.github.com>; 
抄送: "初末流年"<1669487366@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [nestcn/docs.nestjs.cn] 6.0 二次校对认领 (#89)



 
我要认领翻译 [技术(6/techniques) WEBSOCKETS(6/websockets)]
  
高产一哥，认领成功

**Comment by Armor-cn** [comment]
我要认领翻译 [ 应用上下文(6/applicationconte t)  秘籍 (6/recipes)  CLI (6/cli)【已认领】 谁在使用 Nest (6/discover) ]   这几个模块我已经要更新好了，到时候我提PR，你可以发一个新版

**Comment by Armor-cn** [comment]
@zuohuadong  【谁在使用 Nest (6/discover)  这个模块】，我没有更新。

**Comment by Innei** [comment]
自定义装饰器部分 翻译已过时
