### ISSUE TITLE
gitbook不成功

### ISSUE THREAD

**Issue by baby7305** [nestcn/docs.nestjs.cn#98]
能中文文档官网上直接给个pdf链接吗？gitbook就是转换不成功
gitbook FileNotFoundError: No "README" file (or is ignored)

**Comment by zuohuadong** [comment]
抱歉，暂无 PDF ~
这个用的 docsify

**Comment by zuohuadong** [comment]
可以试试sw.js    支持离线模式

**Comment by baby7305** [comment]
直接用了typora，md单页导出了pdf，还行
